services:
  - name: paraprojeto
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn paraprojeto.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
